### ISSUE TITLE
propose logo

### ISSUE THREAD

**Issue by dee-y** [ua1-labs/firestudio#1]
Hello @joshualjohnson  i am a graphic designer. I would like to know if you would be interested in me making a logo for this project. If you would have me, i would make a logo for you, and it's free.

**Comment by joshualjohnson** [comment]
@dee-y I definitely would be interested in reviewing any logos you designed for the FireStudio project. I want to be clear, however, that if you do decide to contribute any of your work to this project, you must allow for redistribution royalty-free and provide permissions for modifications without your direct approval.

**Comment by dee-y** [comment]
I agree to your terms @joshualjohnson, i have designed the logo below. What do you think?

![firestudio-01](https://user-images.githubusercontent.com/36637989/41951659-e464487e-79c3-11e8-8aaf-c51c5f863eb2.jpg)

the designs at the top of the "F" represent data, content sharing. While the oval line that goes round the "F" represents internet or web...

**Comment by joshualjohnson** [comment]
I like the concept and think it is off to a really good start. Take a look at the design we have so far in the admin area of this application. 

<img width="1145" alt="screen shot 2018-06-27 at 4 24 25 pm" src="https://user-images.githubusercontent.com/9388565/41997848-2ac493c4-7a27-11e8-9094-060b565f5325.png">

Please try to use these colors, Also, I do not like the oval around the F.

**Comment by dee-y** [comment]
Hi @joshualjohnson i have made the changes you requested. What do you think of this version...do you prefer the first text or second? or if you have another preference please let me know. More changes are welcomed!

![firestudio2-01](https://user-images.githubusercontent.com/36637989/42057652-f6524c54-7b15-11e8-9f2d-c5741add2c6d.png)

**Comment by joshualjohnson** [comment]
It's really looking a lot more along the lines of what I was thinking! I like the second font style better but would like the "Fire" to be more bold. I'm not exactly sure what is missing, but I think it might look better at the same font-weight as the "Studio" portion of the logo. I don't think we need to separate "fire" from "studio". I do love the piece off the "F" though and what it represents.

**Comment by dee-y** [comment]
Hi @joshualjohnson, did you mean something more like this?
![firestudio](https://user-images.githubusercontent.com/36637989/42107847-b26a735c-7bd0-11e8-8bc8-84608611046b.png)

**Comment by joshualjohnson** [comment]
One more tweak and I think we've got it! Go a little less bold on the piece that attaches to the F. I don't think it should be the same line-weight as the F is. Just a hair smaller. What do you think?

Other than that! Thank you for reaching out and initiating the discussion around the logo! Once those changes are complete, I'll give you next steps on how we will integrate into the project.

**Comment by dee-y** [comment]
How about this? 
![firestudio22](https://user-images.githubusercontent.com/36637989/42125815-b6932320-7c75-11e8-9454-83230ecfb8f0.png)

**Comment by joshualjohnson** [comment]
YES! That is the one. With that being said, could you please provide:
* A dark version of the logo
* A light version of the logo
* A square version of the full logo stacked - Fire (top line) and Studio (bottom line) - Light and Dark version
* An icon version of the logo with just the "F" - Light and dark versions
* Please be sure to include transparent backgrounds on all logos and send them over in the PNG format.
* Please also include a small, medium, large, x-large version of each logo according to industry standards. 
* To submit these logos to the code base, you may submit a Pull Request with the logos you've created. Please include them in a directory called "logos" at the root of the project. You may create a pull request by "Forking" the repo, committing your changes, and then clicking "Compare" within your fork. In the pull request please confirm that you are the original artist of the logos.

**Comment by dee-y** [comment]
Hi @joshualjohnson, i have exported all versions of the logo you requested in PNG, and also uploaded them with their editable formats here at google drive link for your download https://drive.google.com/drive/folders/1HTtto_0pcC9RgTUAROJCcH-iOWiKEAqO?usp=sharing

I also made the pull request containing all versions of the logo files as well as the logo licence for ownership here https://github.com/ua1-labs/firestudio/pull/2

Best regards,
Dee-y.

**Comment by joshualjohnson** [comment]
Closing this issue.

Thanks Dee-y!

**Comment by dee-y** [comment]
Great @joshualjohnson, can't wait to see how the logo looks on the project!

**Comment by joshualjohnson** [comment]
@dee-y Just thought I'd share with you what your contribution is looking like!
![screenshot from 2018-07-07 07-52-51](https://user-images.githubusercontent.com/9388565/42410647-fde89fee-81ba-11e8-98e5-69bfeeb1da9f.png)
